### ISSUE TITLE
hope you guys setup a colab notebook

### ISSUE THREAD

**Issue by GeorvityLabs** [VinAIResearch/HyperInverter#1]
really cool @VinAIResearch
hope you guys will add a colab notebook were we could test it on colab gpu.

**Comment by di-mi-ta** [comment]
Hi, 
I am so sorry for the late response. Thanks for your interest.  Unfortunately, currently, I am busy with some other work, and releasing the Colab demo will not be my top priority now. We hope you can try HyperInverter on your local machine at this time since we released all source code and pre-trained models.
Thanks!
Best regards, 
Tan M. Dinh
