### ISSUE TITLE
Please upload a few of the test images used in the paper to compare results

### ISSUE THREAD

**Issue by Mayorc1978** [VinAIResearch/HyperInverter#3]
Please, upload some of the face test images shown in the paper so I can validate and evaluate my inference results with those images with the results shown on Hyperinverter papers and that they are comparable.

Thanks.

**Comment by di-mi-ta** [comment]
Hi, 

To visualize the results on the paper and supplementary,  we use some images from the CelebA-HQ test set and some in-the-wild images from the Internet. Due to the license, we are not sure that we can upload these images here. Therefore, we can give you the filenames of some images in the CelebA-HQ test set we use in the paper + supp that you can try, which are: 00453, 00600, 00726, 02187, 02225, 02370, 02940, 08486, 00127, 02097, 11080, 11144, 11331, 13937, 16590, 08419, 09322, 12290, 12701, 13098, 15614, 15929, 17695, 17896, 18163, 18602, 27426, 17499, 15439, 27069, 28980, 14846, 02370, 24268. For the images from Internet, you can search the keywords like Jürgen Klopp, Hillary Clinton, Thomas Tuchel, etc.

Thanks!
Best regards,
Tan M. Dinh
